/* board.c - clocks, pins, MPU and the millisecond tick (see board.h). */
#include "board.h"

#include "clock_config.h"   /* generated by MCUXpresso Config Tools */
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "pin_mux.h"        /* generated by MCUXpresso Config Tools */

/* Provided by the SDK board template (board.c of the EVK, adapted): the MPU regions,
 * including the non-cacheable OCRAM section the USB and ENET DMA buffers use. */
extern void BOARD_ConfigMPU(void);

#define BOARD_XTAL_HZ 24000000u

static volatile uint32_t s_ms;

void SysTick_Handler(void) { s_ms++; }

void board_init(void)
{
    BOARD_ConfigMPU();
    BOARD_InitBootPins();
    BOARD_InitBootClocks();
    SysTick_Config(SystemCoreClock / 1000u);

    gpio_pin_config_t out = {kGPIO_DigitalOutput, 0, kGPIO_NoIntmode};
    GPIO_PinInit(BOARD_NESSUM_RST_GPIO, BOARD_NESSUM_RST_PIN, &out);   /* IC held in reset */

    /* USB1 PHY and PLL (as TinyUSB's hw/bsp/imxrt/family.c) */
    CLOCK_EnableUsbhs0PhyPllClock(kCLOCK_Usbphy480M, BOARD_XTAL_HZ);
    CLOCK_EnableUsbhs0Clock(kCLOCK_Usb480M, BOARD_XTAL_HZ);
    USBPHY1->CTRL |= USBPHY_CTRL_SET_ENUTMILEVEL2_MASK | USBPHY_CTRL_SET_ENUTMILEVEL3_MASK;
    USBPHY1->PWD = 0;
    uint32_t tx = USBPHY1->TX & ~(USBPHY_TX_D_CAL_MASK | USBPHY_TX_TXCAL45DM_MASK | USBPHY_TX_TXCAL45DP_MASK);
    USBPHY1->TX = tx | USBPHY_TX_D_CAL(0x0C) | USBPHY_TX_TXCAL45DP(0x06) | USBPHY_TX_TXCAL45DM(0x06);
}

uint32_t board_millis(void) { return s_ms; }

void board_delay_ms(uint32_t ms)
{
    uint32_t t0 = s_ms;
    while (s_ms - t0 < ms) {
    }
}

/* LPI2C and LPUART clock roots: 60 MHz / 80 MHz PLL3 derived in the EVK clock config.
 * Divide by the configured dividers so a Config Tools change is followed. */
uint32_t board_lpi2c_clock_hz(void)
{
    return (CLOCK_GetFreq(kCLOCK_Usb1PllClk) / 8u) / (CLOCK_GetDiv(kCLOCK_Lpi2cDiv) + 1u);
}

uint32_t board_lpuart_clock_hz(void)
{
    return (CLOCK_GetFreq(kCLOCK_Usb1PllClk) / 6u) / (CLOCK_GetDiv(kCLOCK_UartDiv) + 1u);
}

void board_nessum_reset(bool asserted)
{
    GPIO_PinWrite(BOARD_NESSUM_RST_GPIO, BOARD_NESSUM_RST_PIN, asserted ? 0u : 1u);
}
