/* enet_bridge.c - see enet_bridge.h. */
#include "enet_bridge.h"

#include <string.h>

#include "board.h"
#include "fsl_clock.h"
#include "fsl_enet.h"
#include "fsl_iomuxc.h"
#include "ncm.h"
#include "usb_ncm.h"

#define RX_BD 8
#define TX_BD 8
#define BUF_SIZE SDK_SIZEALIGN(ENET_FRAME_MAX_FRAMELEN + 4u, ENET_BUFF_ALIGNMENT)   /* + VLAN tag */
#define TX_WAIT_MS 2u   /* bounded wait for a TX descriptor before dropping */

AT_NONCACHEABLE_SECTION_ALIGN(static enet_rx_bd_struct_t s_rx_bd[RX_BD], ENET_BUFF_ALIGNMENT);
AT_NONCACHEABLE_SECTION_ALIGN(static enet_tx_bd_struct_t s_tx_bd[TX_BD], ENET_BUFF_ALIGNMENT);
AT_NONCACHEABLE_SECTION_ALIGN(static uint8_t s_rx_buf[RX_BD][BUF_SIZE], ENET_BUFF_ALIGNMENT);
AT_NONCACHEABLE_SECTION_ALIGN(static uint8_t s_tx_buf[TX_BD][BUF_SIZE], ENET_BUFF_ALIGNMENT);

static enet_handle_t s_handle;
static enet_frame_info_t s_tx_info[TX_BD];
static uint8_t s_frame[BUF_SIZE];   /* the frame waiting for room on the USB side */
static uint32_t s_frame_len;
static enet_bridge_stats_t s_stats;
static bool s_ready;

const enet_bridge_stats_t *enet_bridge_stats(void) { return &s_stats; }

bool enet_bridge_init(const uint8_t mac[6])
{
    /* RMII 50 MHz reference: generated by the ENET PLL and driven out on ENET_REF_CLK
     * (the 50 MHz oscillator footprint stays unpopulated). If the board takes the
     * oscillator instead, clear ENET1TxClkOutputDir and skip the PLL. */
    const clock_enet_pll_config_t pll = {.enableClkOutput = true, .loopDivider = 1 /* 50 MHz */};
    CLOCK_InitEnetPll(&pll);
    IOMUXC_EnableMode(IOMUXC_GPR, kIOMUXC_GPR_ENET1TxClkOutputDir, true);

    enet_config_t cfg;
    ENET_GetDefaultConfig(&cfg);
    cfg.miiMode = kENET_RmiiMode;
    cfg.miiSpeed = kENET_MiiSpeed100M;
    cfg.miiDuplex = kENET_MiiFullDuplex;
    cfg.rxMaxFrameLen = ENET_FRAME_MAX_FRAMELEN + 4u;
    cfg.macSpecialConfig = kENET_ControlPromiscuousEnable;   /* also: no flow control */

    enet_buffer_config_t buf = {
        .rxBdNumber = RX_BD,
        .txBdNumber = TX_BD,
        .rxBuffSizeAlign = BUF_SIZE,
        .txBuffSizeAlign = BUF_SIZE,
        .rxBdStartAddrAlign = s_rx_bd,
        .txBdStartAddrAlign = s_tx_bd,
        .rxBufferAlign = &s_rx_buf[0][0],
        .txBufferAlign = &s_tx_buf[0][0],
        .rxMaintainEnable = false,   /* buffers are non-cacheable */
        .txMaintainEnable = false,
        .txFrameInfo = s_tx_info,
    };
    uint8_t addr[6];
    memcpy(addr, mac, 6);   /* unused in promiscuous mode, but the driver wants one */
    if (ENET_Init(ENET, &s_handle, &cfg, &buf, addr, CLOCK_GetFreq(kCLOCK_IpgClk)) != kStatus_Success)
        return false;
    ENET_ActiveRead(ENET);
    s_ready = true;
    return true;
}

/* Called by usb_ncm.c for each frame of a validated NTB (host -> Nessum). */
bool ncm_dev_from_host(const uint8_t *frame, size_t len)
{
    uint32_t t0 = board_millis();
    for (;;) {
        status_t st = ENET_SendFrame(ENET, &s_handle, frame, (uint32_t)len, 0, false, NULL);
        if (st == kStatus_Success) {
            s_stats.tx_frames++;
            return true;
        }
        if (st != kStatus_ENET_TxFrameBusy || board_millis() - t0 > TX_WAIT_MS) {
            s_stats.tx_dropped++;
            return false;
        }
        ENET_ReclaimTxDescriptor(ENET, &s_handle, 0);
    }
}

void enet_bridge_poll(void)
{
    if (!s_ready)   /* also called while boot-time Nessum commands wait */
        return;
    for (int budget = RX_BD; budget > 0; budget--) {
        if (s_frame_len) {                       /* waiting for the USB side */
            if (!ncm_dev_active()) {
                s_stats.rx_dropped++;
            } else if (!ncm_dev_to_host(s_frame, s_frame_len)) {
                return;                          /* NTB buffers busy: retry next loop */
            }
            s_frame_len = 0;
        }
        uint32_t len = 0;
        status_t st = ENET_GetRxFrameSize(&s_handle, &len, 0);
        if (st == kStatus_ENET_RxFrameEmpty)
            return;
        if (st != kStatus_Success || len < NCM_ETH_MIN || len > NCM_ETH_MAX) {
            ENET_ReadFrame(ENET, &s_handle, NULL, 0, 0, NULL);   /* discard */
            s_stats.rx_errors++;
            continue;
        }
        if (ENET_ReadFrame(ENET, &s_handle, s_frame, len, 0, NULL) == kStatus_Success) {
            s_stats.rx_frames++;
            s_frame_len = len;
        }
    }
}
