#!/usr/bin/env python3
"""Derive the bootloader and application linker scripts from the SDK's
MIMXRT1062xxxxx_flexspi_nor.ld (BSD-3-Clause, NXP) by replacing its MEMORY block.

    gen_ld.py boot|app <sdk .ld> <output .ld>

boot: the SDK layout, text capped so the whole bootloader fits in 64 KB.
app:  runs from the active slot: vector table at 0x60010400 (FW_ACTIVE_LOAD_ADDR),
      after the 1 KB image header; the FCB/IVT regions are empty (no boot header).
Fails if the SDK script no longer has the expected MEMORY block.
"""
import re
import sys

EXPECTED = [
    ("m_flash_config", "0x60000000", "0x00001000"),
    ("m_ivt", "0x60001000", "0x00001000"),
    ("m_interrupts", "0x60002000", "0x00000400"),
    ("m_text", "0x60002400", "TEXT_SIZE"),
]

LAYOUTS = {
    "boot": {"m_text": ("0x60002400", "0x0000DC00")},          # 0x60000000 + 64 KB
    "app": {
        "m_flash_config": ("0x60010000", "0x00000200"),        # unused (no boot header)
        "m_ivt": ("0x60010200", "0x00000200"),                 # unused
        "m_interrupts": ("0x60010400", "0x00000400"),          # FW_ACTIVE_LOAD_ADDR
        "m_text": ("0x60010800", "0x000FF800"),                # rest of the 1 MB slot
    },
}


def main(kind, src, dst):
    with open(src) as f:
        text = f.read()
    for name, origin, length in EXPECTED:
        pat = r"(%s\s+\(RX\)\s+:\s+ORIGIN = )%s(, LENGTH = )%s" % (name, origin, length)
        if not re.search(pat, text):
            sys.exit(f"gen_ld.py: {src}: unexpected MEMORY entry for {name} (SDK changed?)")
    for name, (origin, length) in LAYOUTS[kind].items():
        old = next(e for e in EXPECTED if e[0] == name)
        pat = r"(%s\s+\(RX\)\s+:\s+ORIGIN = )%s(, LENGTH = )%s" % (name, old[1], old[2])
        text = re.sub(pat, r"\g<1>%s\g<2>%s" % (origin, length), text)
    note = f"/* GENERATED by firmware/platform/rt1062/gen_ld.py ({kind}) from the NXP SDK script below. */\n"
    with open(dst, "w") as f:
        f.write(note + text)


if __name__ == "__main__":
    if len(sys.argv) != 4 or sys.argv[1] not in LAYOUTS:
        sys.exit(__doc__)
    main(*sys.argv[1:])
